# Generated by Django 4.1.6 on 2023-02-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelz', '0002_post_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
