# Generated by Django 4.1.6 on 2023-03-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheelz', '0003_alter_post_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pic',
        ),
    ]
