# Generated by Django 4.1.6 on 2023-03-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelz', '0004_remove_post_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_images',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
